# Generated by Django 3.1.7 on 2021-04-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', '-delivery_at']},
        ),
    ]
